### ISSUE TITLE
Fan speed didn't work MBP 15 2018

### ISSUE THREAD

**Issue by IanWazowski** [Moneypulation/iGlance#9] opened 2019-01-06 14:56 UTC

**Comment by D0miH** [comment] 2019-01-07 08:53
Hi Ian, 

thanks for opening this issue. Since I habe a MBP 15' 2018 as well, I am aware of this issue. 
However the problem lies within the SMCKit library. It seems like the smc-key for retrieving the information about the fans is not working. 

Apparently the [smcFanControl](https://github.com/hholtmann/smcFanControl) tool is able to read the fan speeds on a 2018 MBP. However [this](https://github.com/hholtmann/smcFanControl/issues/77) issue indicates that the values are not correct.

One possibility we could try, is to look into the code of the [smcFanControl](https://github.com/hholtmann/smcFanControl) project and see how they retrieve the information about the fans.

**Comment by D0miH** [comment] 2019-01-17 08:32
Ok so I looked into the issue and apparently, the problem is in the `updateFanSpeed()` method in the `AppDelegate.swift` file. The problem is that trying to get the fan information will fail on the 2018 MacBook Pro. In the method however after the failed result, the function returns.

We could solve this, by not retrieving the fan information, but instead get the number of fans and directly get the current rpm of the fans. 

I will look into this and eventually update the app.

**Comment by D0miH** [comment] 2019-01-23 16:17
Should be fixed by #12

**Closed by D0miH** 2019-01-23 16:17 UTC
Labels: bug
